/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HomeCarouselResponseData } from '../../models/home-carousel-response-data';

export interface ApiCarouselDeleteCarouselDelete$Params {

/**
 * 要刪除的輪播圖 Id(GUID),以 query string 傳遞:?carouselId=...
 */
  carouselId?: string;
}

export function apiCarouselDeleteCarouselDelete(http: HttpClient, rootUrl: string, params?: ApiCarouselDeleteCarouselDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<HomeCarouselResponseData>> {
  const rb = new RequestBuilder(rootUrl, apiCarouselDeleteCarouselDelete.PATH, 'delete');
  if (params) {
    rb.query('carouselId', params.carouselId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HomeCarouselResponseData>;
    })
  );
}

apiCarouselDeleteCarouselDelete.PATH = '/api/Carousel/DeleteCarousel';
