/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HomeCarouselResponseData } from '../../models/home-carousel-response-data';

export interface ApiCarouselCreateCarouselPicturesPost$Params {
      body?: {

/**
 * 輪播圖片檔(jpeg/png/webp/gif,上限 10MB)
 */
'picture': Blob;

/**
 * 標題(最多 50 字)
 */
'title': string;

/**
 * 點擊後導向的連結(最多 50 字,可空)
 */
'url'?: string;

/**
 * 是否啟用顯示
 */
'status'?: boolean;
}
}

export function apiCarouselCreateCarouselPicturesPost(http: HttpClient, rootUrl: string, params?: ApiCarouselCreateCarouselPicturesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<HomeCarouselResponseData>> {
  const rb = new RequestBuilder(rootUrl, apiCarouselCreateCarouselPicturesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HomeCarouselResponseData>;
    })
  );
}

apiCarouselCreateCarouselPicturesPost.PATH = '/api/Carousel/CreateCarouselPictures';
