/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SearchHomeCarouselModelListResponseData } from '../../models/search-home-carousel-model-list-response-data';

export interface ApiCarouselSearchCarouselPicturesGet$Params {
}

export function apiCarouselSearchCarouselPicturesGet(http: HttpClient, rootUrl: string, params?: ApiCarouselSearchCarouselPicturesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SearchHomeCarouselModelListResponseData>> {
  const rb = new RequestBuilder(rootUrl, apiCarouselSearchCarouselPicturesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SearchHomeCarouselModelListResponseData>;
    })
  );
}

apiCarouselSearchCarouselPicturesGet.PATH = '/api/Carousel/SearchCarouselPictures';
