/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoryModel } from './models/category-model';
export type { Grit } from './models/grit';
export type { GritDetailModel } from './models/grit-detail-model';
export type { GritModel } from './models/grit-model';
export type { HomeCarousel } from './models/home-carousel';
export type { HomeCarouselResponseData } from './models/home-carousel-response-data';
export type { ImagePaginationModel } from './models/image-pagination-model';
export type { ImagePaginationModelResponseData } from './models/image-pagination-model-response-data';
export type { NewListModel } from './models/new-list-model';
export type { NewModel } from './models/new-model';
export type { News } from './models/news';
export type { NewsModel } from './models/news-model';
export type { NewsModelResponseData } from './models/news-model-response-data';
export type { NewsPaginationModel } from './models/news-pagination-model';
export type { NewsResponseData } from './models/news-response-data';
export type { NewsSearchParametersModel } from './models/news-search-parameters-model';
export type { Product } from './models/product';
export type { ProductSpec } from './models/product-spec';
export type { ProductCategory } from './models/product-category';
export type { ProductCategoryResponseData } from './models/product-category-response-data';
export type { ProductDetailModel } from './models/product-detail-model';
export type { ProductDetailModelResponseData } from './models/product-detail-model-response-data';
export type { ProductPaginationModel } from './models/product-pagination-model';
export type { ProductPaginationModelResponseData } from './models/product-pagination-model-response-data';
export type { ProductPicture } from './models/product-picture';
export type { ProductPictureModel } from './models/product-picture-model';
export type { ProductSearchResModel } from './models/product-search-res-model';
export type { Response } from './models/response';
export type { S3PictureModel } from './models/s-3-picture-model';
export type { SearchCategoryModel } from './models/search-category-model';
export type { SearchCategoryModelListResponseData } from './models/search-category-model-list-response-data';
export type { SearchHomeCarouselModel } from './models/search-home-carousel-model';
export type { SearchHomeCarouselModelListResponseData } from './models/search-home-carousel-model-list-response-data';
export type { StringIReadOnlyListResponseData } from './models/string-i-read-only-list-response-data';
