/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 建立/更新產品分類的傳入資料
 */
export interface CategoryModel {

  /**
   * 分類 Id。建立時忽略;更新時必填
   */
  id?: string | null;

  /**
   * 分類簡介(可空)
   */
  introduction?: string | null;

  /**
   * 分類名稱(最多 50 字)
   */
  name: string;

  /**
   * 排序值。建立時忽略(自動排最後);更新時會覆寫
   */
  orders?: number;

  /**
   * 父分類 Id。主分類留空;次分類帶主分類的 Id
   */
  parentId?: string | null;

  /**
   * 是否啟用
   */
  status?: boolean;
}
