/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';
export interface Grit {
  grit_size?: string | null;
  id?: string;
  price?: number | null;
  product?: Product;
  product_id?: string | null;
}
