/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 番號詳情(含 Id,供編輯頁識別現有項目)
 */
export interface GritDetailModel {
  grit?: string | null;
  id?: string;
  price?: number;
}
