/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 產品番號與價格
 */
export interface GritModel {

  /**
   * 番號(粒度規格),例如 "#80"(最多 50 字)
   */
  grit: string;

  /**
   * 價格(新台幣,不可為負數)
   */
  price?: number;
}
