/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 首頁輪播圖(資料庫實體,出現在新增/刪除輪播圖的回應中)
 */
export interface HomeCarousel {

  /**
   * 輪播圖 Id
   */
  id?: string;

  /**
   * 排序值(越小越前面)
   */
  orders?: number;

  /**
   * 圖片的 S3 內部路徑(非可直接顯示的網址;顯示請用查詢端點回傳的 image)
   */
  picture: string;

  /**
   * 是否啟用顯示
   */
  status?: boolean;

  /**
   * 標題
   */
  title?: string | null;

  /**
   * 點擊後導向的連結(可能為 null)
   */
  url?: string | null;
}
