/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { S3PictureModel } from '../models/s-3-picture-model';

/**
 * 圖庫圖片的分頁查詢結果(平鋪列表,含目錄資訊)
 */
export interface ImagePaginationModel {

  /**
   * 當頁圖片列表
   */
  images?: Array<S3PictureModel> | null;

  /**
   * 符合篩選條件的圖片總數
   */
  totalCount?: number;
}
