/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 消息列表中的單筆摘要(不含內文)
 */
export interface NewListModel {

  /**
   * 分類名稱
   */
  classification?: string | null;

  /**
   * 發布日期,格式 yyyy-MM-dd
   */
  date?: string | null;

  /**
   * 消息 Id
   */
  id?: string;

  /**
   * 列表頁簡介(可能為 null)
   */
  introduction?: string | null;

  /**
   * 顯示用排序序號(資料庫排序值除以 10)
   */
  orders?: number;

  /**
   * 是否上架顯示
   */
  status?: boolean;

  /**
   * 消息標題
   */
  title?: string | null;
}
