/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 建立/更新最新消息的傳入資料
 */
export interface NewModel {

  /**
   * 消息分類名稱(最多 50 字)
   */
  classification: string;

  /**
   * 發布日期(ISO 8601 格式,例如 2026-06-11T00:00:00)
   */
  date?: string;

  /**
   * 消息 Id。新增時留空(null);更新時必填
   */
  id?: string | null;

  /**
   * 列表頁顯示的簡介(最多 100 字,可空)
   */
  introduction?: string | null;

  /**
   * 消息內文(HTML 字串,無長度限制)
   */
  newContent: string;

  /**
   * 是否上架顯示
   */
  status?: boolean;

  /**
   * 消息標題(最多 50 字)
   */
  title: string;
}
