/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 單筆消息的完整內容(預覽/編輯用)
 */
export interface NewsModel {

  /**
   * 分類名稱
   */
  classification?: string | null;

  /**
   * 發布日期,格式 yyyy-MM-dd
   */
  date?: string | null;

  /**
   * 消息 Id
   */
  id?: string;

  /**
   * 列表頁簡介(可能為 null)
   */
  introduction?: string | null;

  /**
   * 消息內文(HTML 字串)
   */
  newContent?: string | null;

  /**
   * 是否上架顯示
   */
  status?: boolean;

  /**
   * 消息標題
   */
  title?: string | null;
}
