/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 最新消息列表的查詢條件
 */
export interface NewsSearchParametersModel {

  /**
   * 依分類名稱精準篩選;null 或空字串代表不篩選
   */
  classification?: string | null;

  /**
   * 標題關鍵字(模糊比對);null 或空字串代表不篩選
   */
  keyword?: string | null;

  /**
   * 每頁筆數;省略時預設 10
   */
  newsCount?: number | null;

  /**
   * 頁碼,從 0 開始
   */
  pageIndex?: number;

  /**
   * 依上架狀態篩選;null 代表不篩選
   */
  status?: boolean | null;
}
