/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 最新消息(資料庫實體,出現在建立/更新消息的回應中)
 */
export interface News {

  /**
   * 分類名稱
   */
  classification: string;

  /**
   * 發布日期(ISO 8601)
   */
  date?: string;

  /**
   * 消息 Id
   */
  id?: string;

  /**
   * 列表頁簡介(可能為 null)
   */
  introduction?: string | null;

  /**
   * 消息內文(HTML 字串)
   */
  newContent: string;

  /**
   * 排序值(越小越前面)
   */
  orders?: number;

  /**
   * 是否上架顯示
   */
  status?: boolean;

  /**
   * 消息標題
   */
  title: string;
}
