/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NewsModel } from '../models/news-model';

/**
 * 帶資料的統一回應包裝。JSON 形狀:{ data, code, message, isSuccess }
 */
export interface NewsModelResponseData {

  /**
   * 業務狀態碼。200 為成功,其餘為失敗(404 找不到資料、400 輸入錯誤、500 系統錯誤)
   */
  code?: number;
  data?: NewsModel;

  /**
   * 操作是否成功。注意:HTTP 200 時也可能為 false(例如排序已到頂/到底)
   */
  isSuccess?: boolean;

  /**
   * 給使用者看的訊息(繁體中文),可直接顯示於前端提示
   */
  message?: string | null;
}
