/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NewListModel } from '../models/new-list-model';

/**
 * 消息列表的分頁查詢結果(此模型不使用統一包裝,直接回傳)
 */
export interface NewsPaginationModel {

  /**
   * 當前頁的消息列表
   */
  newsList?: Array<NewListModel> | null;

  /**
   * 符合篩選條件的總筆數(用於計算總頁數)
   */
  totalCount?: number;
}
