/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 圖片詳情(含 Id,供編輯頁決定保留或刪除)
 */
export interface ProductPictureModel {
  id?: string;

  /**
   * S3 預簽名網址(10 分鐘有效)
   */
  url?: string | null;
}
