/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Grit } from '../models/grit';
import { ProductSpec } from '../models/product-spec';
import { ProductCategory } from '../models/product-category';
import { ProductPicture } from '../models/product-picture';
export interface Product {
  category?: ProductCategory;
  grits?: Array<Grit> | null;
  id?: string;
  is_active?: boolean;
  name: string;
  orders?: number;
  productPicture?: Array<ProductPicture> | null;
  product_Specs?: Array<ProductSpec> | null;
  subCategoryId?: string;
}
