/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 產品列表中的單筆摘要
 */
export interface ProductSearchResModel {

  /**
   * 分類完整名稱,格式「主分類 > 次分類」
   */
  categoryName?: string | null;

  /**
   * 封面圖網址(第一張產品圖的 S3 預簽名網址,10 分鐘有效;沒有圖片時為空字串)
   */
  coverURL?: string | null;

  /**
   * 是否上架
   */
  isActive?: boolean;

  /**
   * 訂購方式顯示文字:「客製化訂製」或「來電詢問」
   */
  orderType?: string | null;

  /**
   * 產品 Id
   */
  productId?: string;

  /**
   * 產品名稱
   */
  productName?: string | null;
}
