/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';

/**
 * 產品分類(資料庫實體,出現在建立/更新分類的回應中)
 */
export interface ProductCategory {

  /**
   * 分類 Id
   */
  id?: string;

  /**
   * 分類簡介(可能為 null)
   */
  introduction?: string | null;

  /**
   * 子分類集合(導覽屬性,API 回應中通常為空陣列,請勿依賴)
   */
  inverseparent?: Array<ProductCategory> | null;

  /**
   * 分類名稱
   */
  name: string;

  /**
   * 排序值(越小越前面)
   */
  orders?: number;
  parent?: ProductCategory;

  /**
   * 父分類 Id;主分類為 null
   */
  parentId?: string | null;

  /**
   * 所屬產品集合(導覽屬性,API 回應中通常為空陣列,請勿依賴)
   */
  products?: Array<Product> | null;

  /**
   * 是否啟用
   */
  status?: boolean;
}
