/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductSearchResModel } from '../models/product-search-res-model';

/**
 * 產品列表的分頁查詢結果
 */
export interface ProductPaginationModel {

  /**
   * 當前頁的產品列表
   */
  productList?: Array<ProductSearchResModel> | null;

  /**
   * 符合篩選條件的總筆數(用於計算總頁數)
   */
  totalCount?: number;
}
