/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GritDetailModel } from '../models/grit-detail-model';
import { ProductPictureModel } from '../models/product-picture-model';

/**
 * 單一產品完整詳情(供編輯頁使用)
 */
export interface ProductDetailModel {

  /**
   * 是否可訂購
   */
  canOrder?: boolean;

  /**
   * 分類完整名稱,格式「主分類 > 次分類」
   */
  categoryName?: string | null;

  /**
   * 產品描述
   */
  description?: string | null;

  /**
   * 番號價格表
   */
  grits?: Array<GritDetailModel> | null;

  /**
   * 是否上架
   */
  isActive?: boolean;

  /**
   * 材質
   */
  material?: string | null;

  /**
   * 產品型號
   */
  modelNumber?: string | null;

  /**
   * 產品名稱
   */
  name?: string | null;

  /**
   * 產品圖片清單(含 S3 預簽名網址,10 分鐘有效)
   */
  pictures?: Array<ProductPictureModel> | null;

  /**
   * 產品 Id
   */
  productId?: string;

  /**
   * 規格
   */
  specification?: string | null;

  /**
   * 所屬次分類 Id
   */
  subCategoryId?: string;

  /**
   * 銷售單位
   */
  unit?: string | null;

  /**
   * 用途
   */
  usage?: string | null;
}
