/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';
export interface ProductPicture {
  id?: string;
  product?: Product;
  productId?: string;
  url?: string | null;
}
