/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';
export interface ProductSpec {
  can_order?: boolean;
  description?: string | null;
  equipment?: string | null;
  id?: string;
  material?: string | null;
  model_number?: string | null;
  product?: Product;
  productId?: string | null;
  specification?: string | null;
  unit?: string | null;
  usage?: string | null;
}
