/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 統一回應基底。所有錯誤回應與不帶資料的成功回應都是此形狀:{ code, message, isSuccess }
 */
export interface Response {

  /**
   * 業務狀態碼。200 為成功,其餘為失敗(404 找不到資料、400 輸入錯誤、500 系統錯誤)
   */
  code?: number;

  /**
   * 操作是否成功。注意:HTTP 200 時也可能為 false(例如排序已到頂/到底)
   */
  isSuccess?: boolean;

  /**
   * 給使用者看的訊息(繁體中文),可直接顯示於前端提示
   */
  message?: string | null;
}
