/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 圖庫中的一張圖片(原圖+縮圖一組)
 */
export interface S3PictureModel {

  /**
   * 所在目錄(含結尾斜線),例如 "products/"。刪除時用 directories + 檔名組合 key
   */
  directories?: string | null;

  /**
   * 原圖檔名,例如 "abc.jpg"
   */
  imageName?: string | null;

  /**
   * 縮圖檔名,例如 "abc_Small.jpg"
   */
  smallImageName?: string | null;

  /**
   * 縮圖網址(S3 預簽名,10 分鐘有效)
   */
  smallImageUrl?: string | null;

  /**
   * 原圖網址(S3 預簽名,10 分鐘有效)
   */
  url?: string | null;
}
