/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 輪播圖查詢結果項目;也作為排序端點的傳入資料(排序時只需帶 id)
 */
export interface SearchHomeCarouselModel {

  /**
   * 輪播圖 Id
   */
  id?: string;

  /**
   * 圖片網址(S3 預簽名,10 分鐘有效,可直接放 img src)
   */
  image?: string | null;

  /**
   * 列表中的序號,從 0 開始
   */
  index?: number;

  /**
   * 排序值(越小越前面)
   */
  orders?: number;

  /**
   * 是否啟用顯示
   */
  status?: boolean;

  /**
   * 標題
   */
  title?: string | null;

  /**
   * 點擊後導向的連結(可能為空)
   */
  url?: string | null;
}
