/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 產品分類查詢結果項目;也作為分類排序端點的傳入資料(排序時只需帶 Id)
 */
export interface SearchCategoryModel {

  /**
   * 是否可刪除。false 代表底下還有次分類
   */
  canDelete?: boolean;

  /**
   * 分類 Id
   */
  id?: string;

  /**
   * 列表中的序號,從 1 開始
   */
  index?: number;

  /**
   * 分類簡介(可能為 null)
   */
  introduction?: string | null;

  /**
   * 分類名稱
   */
  name?: string | null;

  /**
   * 排序值(越小越前面)
   */
  orders?: number;

  /**
   * 父分類 Id;主分類為 null
   */
  parentId?: string | null;

  /**
   * 父分類名稱;主分類為 null
   */
  parentName?: string | null;

  /**
   * 是否啟用
   */
  status?: boolean;
}
