/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StringIReadOnlyListResponseData } from '../../models/string-i-read-only-list-response-data';

export interface ApiS3DirectoriesGet$Params {
}

export function apiS3DirectoriesGet(http: HttpClient, rootUrl: string, params?: ApiS3DirectoriesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<StringIReadOnlyListResponseData>> {
  const rb = new RequestBuilder(rootUrl, apiS3DirectoriesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StringIReadOnlyListResponseData>;
    })
  );
}

apiS3DirectoriesGet.PATH = '/api/S3/directories';
