/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImagePaginationModelResponseData } from '../../models/image-pagination-model-response-data';

export interface ApiS3ImagesGet$Params {

/**
 * 目錄過濾關鍵字;null 或空字串代表不篩選
 */
  directory?: string;

/**
 * 頁碼,從 0 開始
 */
  pageIndex?: number;

/**
 * 每頁筆數;省略時預設 20
 */
  pageSize?: number;
}

export function apiS3ImagesGet(http: HttpClient, rootUrl: string, params?: ApiS3ImagesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ImagePaginationModelResponseData>> {
  const rb = new RequestBuilder(rootUrl, apiS3ImagesGet.PATH, 'get');
  if (params) {
    rb.query('directory', params.directory, {});
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImagePaginationModelResponseData>;
    })
  );
}

apiS3ImagesGet.PATH = '/api/S3/images';
