/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiS3DeleteImagesDelete$Params {

/**
 * 原圖完整 key
 */
  imageKey?: string;

/**
 * 縮圖完整 key
 */
  smallImageKey?: string;
}

export function apiS3DeleteImagesDelete(http: HttpClient, rootUrl: string, params?: ApiS3DeleteImagesDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiS3DeleteImagesDelete.PATH, 'delete');
  if (params) {
    rb.query('imageKey', params.imageKey, {});
    rb.query('smallImageKey', params.smallImageKey, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiS3DeleteImagesDelete.PATH = '/api/S3/deleteImages';
