/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Response } from '../../models/response';

export interface ApiProductRemoveCategoryIdParentIdDelete$Params {

/**
 * 要刪除的分類 Id(GUID)
 */
  id: string;

/**
 * 該分類的父分類 Id;主分類不帶此參數
 */
  parentId: string;
}

export function apiProductRemoveCategoryIdParentIdDelete(http: HttpClient, rootUrl: string, params: ApiProductRemoveCategoryIdParentIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<Response>> {
  const rb = new RequestBuilder(rootUrl, apiProductRemoveCategoryIdParentIdDelete.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('parentId', params.parentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Response>;
    })
  );
}

apiProductRemoveCategoryIdParentIdDelete.PATH = '/api/Product/RemoveCategory/{id}/{parentId}';
