/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GritModel } from '../../models/grit-model';
import { Response } from '../../models/response';

export interface ApiProductEditProductPut$Params {
      body?: {

/**
 * 要編輯的產品 Id
 */
'ProductId': string;

/**
 * 要保留的現有圖片 Id 清單。
 * 不在清單內的現有圖片會從 S3 和資料庫刪除。
 * Pictures 欄位則承載本次要新增的圖片。
 */
'KeepPictureIds'?: Array<string>;

/**
 * 產品名稱(最多 50 字)
 */
'Name': string;

/**
 * 是否上架
 */
'IsActive'?: boolean;

/**
 * 銷售單位,例如「箱」「包」(最多 50 字)
 */
'Unit'?: string;

/**
 * 產品型號(最多 50 字)
 */
'ModelNumber'?: string;

/**
 * 材質(最多 50 字)
 */
'Material'?: string;

/**
 * 用途(最多 50 字)
 */
'Usage'?: string;

/**
 * 規格(最多 50 字)
 */
'Specification'?: string;

/**
 * 產品描述(無長度限制)
 */
'Description'?: string;

/**
 * 是否可訂購。true 顯示「客製化訂製」;false 顯示「來電詢問」
 */
'CanOrder'?: boolean;

/**
 * 番號價格表。表單格式:Grits[0].Grit、Grits[0].Price、Grits[1].Grit ...
 */
'Grits'?: Array<GritModel>;

/**
 * 產品圖片(可多張,第一張會作為列表封面;jpeg/png/webp/gif,單張上限 10MB)
 */
'Pictures'?: Array<Blob>;

/**
 * 所屬次分類 Id(產品必須掛在次分類底下)
 */
'SubCategoryId': string;
}
}

export function apiProductEditProductPut(http: HttpClient, rootUrl: string, params?: ApiProductEditProductPut$Params, context?: HttpContext): Observable<StrictHttpResponse<Response>> {
  const rb = new RequestBuilder(rootUrl, apiProductEditProductPut.PATH, 'put');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Response>;
    })
  );
}

apiProductEditProductPut.PATH = '/api/Product/EditProduct';
