/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Response } from '../../models/response';
import { SearchCategoryModel } from '../../models/search-category-model';

export interface ApiProductEditCategorySortTypeDirectionPut$Params {

/**
 * 分類層級:`main`(主分類)或其他值(次分類)
 */
  type: string;

/**
 * 移動方向:`up` 或 `down`
 */
  direction: string;
  
    /**
     * 只需要帶 Id(要移動的分類 Id),其餘欄位可省略
     */
    body?: SearchCategoryModel
}

export function apiProductEditCategorySortTypeDirectionPut(http: HttpClient, rootUrl: string, params: ApiProductEditCategorySortTypeDirectionPut$Params, context?: HttpContext): Observable<StrictHttpResponse<Response>> {
  const rb = new RequestBuilder(rootUrl, apiProductEditCategorySortTypeDirectionPut.PATH, 'put');
  if (params) {
    rb.path('type', params.type, {});
    rb.path('direction', params.direction, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Response>;
    })
  );
}

apiProductEditCategorySortTypeDirectionPut.PATH = '/api/Product/EditCategorySort/{type}/{direction}';
