/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SearchCategoryModelListResponseData } from '../../models/search-category-model-list-response-data';

export interface ApiProductSearchCateGoryGet$Params {

/**
 * 主分類 Id(GUID 字串);傳 null 或省略代表查主分類
 */
  categoryId?: string;

/**
 * true 時回傳所有次分類
 */
  nextLayer?: boolean;
}

export function apiProductSearchCateGoryGet(http: HttpClient, rootUrl: string, params?: ApiProductSearchCateGoryGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SearchCategoryModelListResponseData>> {
  const rb = new RequestBuilder(rootUrl, apiProductSearchCateGoryGet.PATH, 'get');
  if (params) {
    rb.query('categoryId', params.categoryId, {});
    rb.query('nextLayer', params.nextLayer, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SearchCategoryModelListResponseData>;
    })
  );
}

apiProductSearchCateGoryGet.PATH = '/api/Product/SearchCateGory';
