/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryModel } from '../../models/category-model';
import { ProductCategoryResponseData } from '../../models/product-category-response-data';

export interface ApiProductCreateCategoryPost$Params {
  
    /**
     * 分類內容。Id 與 orders 欄位在建立時會被忽略
     */
    body?: CategoryModel
}

export function apiProductCreateCategoryPost(http: HttpClient, rootUrl: string, params?: ApiProductCreateCategoryPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductCategoryResponseData>> {
  const rb = new RequestBuilder(rootUrl, apiProductCreateCategoryPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductCategoryResponseData>;
    })
  );
}

apiProductCreateCategoryPost.PATH = '/api/Product/CreateCategory';
