/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductPaginationModelResponseData } from '../../models/product-pagination-model-response-data';

export interface ApiProductGetProductsGet$Params {

/**
 * 產品名稱關鍵字(模糊比對);null 或空字串代表不篩選
 */
  keyword?: string;

/**
 * 依次分類 Id 篩選;null 代表不篩選
 */
  categoryId?: string;

/**
 * 依上下架狀態篩選;null 代表不篩選
 */
  isActive?: boolean;

/**
 * 頁碼,從 0 開始
 */
  pageIndex?: number;

/**
 * 每頁筆數;省略時預設 10
 */
  pageSize?: number;
}

export function apiProductGetProductsGet(http: HttpClient, rootUrl: string, params?: ApiProductGetProductsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductPaginationModelResponseData>> {
  const rb = new RequestBuilder(rootUrl, apiProductGetProductsGet.PATH, 'get');
  if (params) {
    rb.query('keyword', params.keyword, {});
    rb.query('categoryId', params.categoryId, {});
    rb.query('isActive', params.isActive, {});
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductPaginationModelResponseData>;
    })
  );
}

apiProductGetProductsGet.PATH = '/api/Product/GetProducts';
