/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Response } from '../../models/response';

export interface ApiProductEditProductSortIdDirectionPut$Params {

/**
 * 要移動的產品 Id(GUID)
 */
  id: string;

/**
 * 移動方向:`up` 或 `down`
 */
  direction: string;
}

export function apiProductEditProductSortIdDirectionPut(http: HttpClient, rootUrl: string, params: ApiProductEditProductSortIdDirectionPut$Params, context?: HttpContext): Observable<StrictHttpResponse<Response>> {
  const rb = new RequestBuilder(rootUrl, apiProductEditProductSortIdDirectionPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('direction', params.direction, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Response>;
    })
  );
}

apiProductEditProductSortIdDirectionPut.PATH = '/api/Product/EditProductSort/{id}/{direction}';
