/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NewsModelResponseData } from '../../models/news-model-response-data';

export interface ApiNewsPreviewNewNewIdGet$Params {

/**
 * 消息的 Id(GUID)
 */
  newId: string;
}

export function apiNewsPreviewNewNewIdGet(http: HttpClient, rootUrl: string, params: ApiNewsPreviewNewNewIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<NewsModelResponseData>> {
  const rb = new RequestBuilder(rootUrl, apiNewsPreviewNewNewIdGet.PATH, 'get');
  if (params) {
    rb.path('newId', params.newId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NewsModelResponseData>;
    })
  );
}

apiNewsPreviewNewNewIdGet.PATH = '/api/News/PreviewNew/{newId}';
