/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NewModel } from '../../models/new-model';
import { NewsResponseData } from '../../models/news-response-data';

export interface ApiNewsCreateNewsPost$Params {
  
    /**
     * 消息內容。新增時 Id 留空;更新時必須帶 Id
     */
    body?: NewModel
}

export function apiNewsCreateNewsPost(http: HttpClient, rootUrl: string, params?: ApiNewsCreateNewsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<NewsResponseData>> {
  const rb = new RequestBuilder(rootUrl, apiNewsCreateNewsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NewsResponseData>;
    })
  );
}

apiNewsCreateNewsPost.PATH = '/api/News/CreateNews';
