/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Response } from '../../models/response';
import { SearchHomeCarouselModel } from '../../models/search-home-carousel-model';

export interface ApiNewsEditNewsSortDirectionPut$Params {

/**
 * 移動方向:`up`(往前移)或 `down`(往後移)
 */
  direction: string;
  
    /**
     * 只需要帶 id(要移動的消息 Id),其餘欄位可省略
     */
    body?: SearchHomeCarouselModel
}

export function apiNewsEditNewsSortDirectionPut(http: HttpClient, rootUrl: string, params: ApiNewsEditNewsSortDirectionPut$Params, context?: HttpContext): Observable<StrictHttpResponse<Response>> {
  const rb = new RequestBuilder(rootUrl, apiNewsEditNewsSortDirectionPut.PATH, 'put');
  if (params) {
    rb.path('direction', params.direction, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Response>;
    })
  );
}

apiNewsEditNewsSortDirectionPut.PATH = '/api/News/EditNewsSort/{direction}';
