/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiNewsDeleteNewsNewIdDelete$Params {

/**
 * 要刪除的消息 Id(GUID)
 */
  newId: string;
}

export function apiNewsDeleteNewsNewIdDelete(http: HttpClient, rootUrl: string, params: ApiNewsDeleteNewsNewIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiNewsDeleteNewsNewIdDelete.PATH, 'delete');
  if (params) {
    rb.path('newId', params.newId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiNewsDeleteNewsNewIdDelete.PATH = '/api/News/DeleteNews/{newId}';
