/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NewsPaginationModel } from '../../models/news-pagination-model';
import { NewsSearchParametersModel } from '../../models/news-search-parameters-model';

export interface ApiNewsNewsPost$Params {
  
    /**
     * 查詢條件。所有篩選欄位皆可省略(回傳全部);pageIndex 從 0 開始
     */
    body?: NewsSearchParametersModel
}

export function apiNewsNewsPost(http: HttpClient, rootUrl: string, params?: ApiNewsNewsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<NewsPaginationModel>> {
  const rb = new RequestBuilder(rootUrl, apiNewsNewsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NewsPaginationModel>;
    })
  );
}

apiNewsNewsPost.PATH = '/api/News/News';
