/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiPictureCreatePicturePost$Params {
      body?: {

/**
 * 圖片檔(jpeg/png/webp/gif,上限 10MB)
 */
'image': Blob;

/**
 * 檔名(不含副檔名),會存成 {directory}/{title}.jpg
 */
'title': string;

/**
 * 目標目錄名稱,例如 "products"
 */
'directory': string;
}
}

export function apiPictureCreatePicturePost(http: HttpClient, rootUrl: string, params?: ApiPictureCreatePicturePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiPictureCreatePicturePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiPictureCreatePicturePost.PATH = '/api/Picture/CreatePicture';
